export interface MarketIntelligenceRow {
  location: string;
  categories: string;
  cereals: string;
  babyFoods: string;
  beverages: string;
  dairy: string;
  frozenFoods: string;
  grainsStaples: string;
  emergingBrands: string;
}

export const marketIntelligenceData: MarketIntelligenceRow[] = [
  { location: "Benue", categories: "Cereals Baby Foods", cereals: "Multi-grain", babyFoods: "Cerelac, Tom brom, Custard", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Nutri bom" },
  { location: "Kano", categories: "Cereals Baby Foods Beverages Dairy Frozen Foods Grains/Staples", cereals: "Whole wheat meal, Goldenvita, Semovita", babyFoods: "Cerelac, NAN, Aptamil", beverages: "Peak, Milo, Bournvita", dairy: "L & Z Yoghurt, Farm fresh, Farm Pride", frozenFoods: "Cheese, Chicken franks, shrimps", grainsStaples: "Royal Stallion Rice, Gerawa Rice, Optimum Rice", emergingBrands: "Kerrygold, Cadbury, Nutribom, Checkers, Miksi" },
  { location: "Lagos", categories: "Cereals Beverages Grains/Staples", cereals: "Nestlé (Golden Morn), Promasidor (Cowbell Choco), NASCO (Cornflakes)", babyFoods: "", beverages: "1. Coca-Cola Nigeria (Coke, Fanta, Sprite) 2. PepsiCo/Seven-Up Bottling Company (Pepsi, Mirinda, 7UP) 3. Chi Limited (Chivita Juices)", dairy: "", frozenFoods: "", grainsStaples: "1. Olam Nigeria (Mama's Pride Rice, Semovita) 2. Dangote Industries (Dangote Salt, Flour, Sugar) 3. Golden Penny (Flour Mills of Nigeria)", emergingBrands: "TGI Group (Big Bull Rice), Sosaco Nigeria (Jago Milk and Foods), Mamador (PZ Wilmar)" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages Dairy", cereals: "Nasco, kellogs, fruit and fibre", babyFoods: "Nestle, Nutricia, peak", beverages: "Peak, kerry gold, three crowns", dairy: "Coca-Cola, chivita, exotic", frozenFoods: "", grainsStaples: "", emergingBrands: "Peak, nestle, nasco, three crowns, and kellogs" },
  { location: "Kano", categories: "Cereals Baby Foods Beverages Dairy Frozen Foods Grains/Staples", cereals: "Masaravita, Goldenvita, Semovita", babyFoods: "Cerelac, NAN, Aptamil", beverages: "Peak, Milo, Bournvita", dairy: "L & Z Yoghurt, Laban Yoghurt, Farm Fresh", frozenFoods: "Cheese, Crabs, shrimps", grainsStaples: "Gerawa Rice, Optimum Rice, Bigbull Rice", emergingBrands: "SMA, Cow & Gate, Nutribom, Dano, Checkers" },
  { location: "Kano", categories: "Cereals Baby Foods Beverages", cereals: "Semolina, Goldenvita, Semovita", babyFoods: "Cerelac, Nutribom, Nutrilac", beverages: "Nido, Loya, Milo", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Top cafe, Kerrygold, Coffee mate, Miralac, Twisco" },
  { location: "Kano", categories: "Cereals Baby Foods Beverages", cereals: "Semolina, Goldenvita, Semovita", babyFoods: "Cerelac, Nutribom, My boy", beverages: "Threecrowns, Cowbell, Milo", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Latyf, Kerrygold, My boy, Miralac, Kremela" },
  { location: "Kano", categories: "Cereals Baby Foods Beverages Dairy", cereals: "Masavita, Goldenvita, Semovita", babyFoods: "Cerelac, NAN, Lactogen", beverages: "Peak, Milo, Bournvita", dairy: "L & Z Yoghurt, SAN Yoghurt, Aljadeeda Yoghurt", frozenFoods: "", grainsStaples: "", emergingBrands: "Lacstar, Kerrygold, My boy, Miralac, Twisco" },
  { location: "Lagos", categories: "Cereals Grains/Staples", cereals: "Nestlé Nigeria Plc, Promasidor Nigeria Ltd, Golden Penny (Flour Mills of Nigeria Plc)", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Bull, wura, Golden penny", emergingBrands: "Big Bull Rice, Wura Foods, Nuli Foods and Ayoola" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages Dairy", cereals: "Golden Morn, Kellog's Corn Flakes, checkers Custard", babyFoods: "Nutriborn, Cerelac, NAN", beverages: "Bornvita, Milo, Peak", dairy: "Peak Milk, Cowbell, Three Crown", frozenFoods: "", grainsStaples: "", emergingBrands: "Mamuda (biscuits)" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages Dairy", cereals: "Golden Morn, Nasco Cornflakes, Kellogs Cornflakes", babyFoods: "NAN, Nutribom, My boy", beverages: "Milo, Bornvita, Ovaltine", dairy: "Peak Milk, Three Crowns, Dano", frozenFoods: "", grainsStaples: "", emergingBrands: "Don't know" },
  { location: "Lagos", categories: "Frozen Foods", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "Sausages, Ice cream, Chicken", grainsStaples: "", emergingBrands: "Chi Farms, Zartech, Sayed Farms, Delifrost, First Kori Heritage" },
  { location: "Benue", categories: "Beverages", cereals: "", babyFoods: "", beverages: "Cadbury, Nestle, Unilever", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Non" },
  { location: "Benue", categories: "Cereals Beverages", cereals: "Nestlé, PepsiCo, Kellogg's Corn Flakes", babyFoods: "", beverages: "Chivita & Hollandia, Seven-Up Bottling Company, Orijin (Guinness Nigeria PLC)", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Benfruit Plant (Teragro Commodities Limited), Farm Pride, Sunvita Cereal, Oat Krunch" },
  { location: "Benue", categories: "Cereals Baby Foods Beverages Frozen Foods", cereals: "Nestle, Friesland, fareast", babyFoods: "Nestle, Friesland, fareast", beverages: "Nestle, Friesland, fareast", dairy: "", frozenFoods: "Zartech, fiesta, anadariya", grainsStaples: "", emergingBrands: "Unilever, plz, Nivea, nestle, fresiland" },
  { location: "Lagos", categories: "Frozen Foods Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "Paramount Frozen Food Ltd, Frozen Food Nigeria Limited, DÉLIFROST", grainsStaples: "BUA Foods Plc, Flour Mills of Nigeria (FMN), Crown Flour Mills", emergingBrands: "Tblizs Foods, The Nut Place, AgroEknor and Potato Foods NG" },
  { location: "Lagos", categories: "Cereals Beverages", cereals: "Golden morn, Coco Pops, Kellogg's Corn Flakes", babyFoods: "", beverages: "Coke cola, Pepsi, Gold breg", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Folay Industries – Pocco Cereals, Oat Krunch, Pedro's Premium Ògógóró and Farm Pride drinks" },
  { location: "Kano", categories: "Cereals Baby Foods Beverages Grains/Staples", cereals: "Maize flour, Guinea corn flour, Cassava Flour", babyFoods: "Cerelac, Custard, golden morn", beverages: "cowbell milk, milo, Bournvita", dairy: "", frozenFoods: "", grainsStaples: "Rice, Maize, Millet", emergingBrands: "Top cafe, Kerrygold, Coffee mate, Crown, Twisco" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages", cereals: "Quarker oats, Nasco, kellogs", babyFoods: "Nestle, SMA, Aptamil", beverages: "Coca-Cola, Nestle, chi limited", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Muamal beverage" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages Dairy", cereals: "Kellogs, Nasco and Mr brown", babyFoods: "NAN, my boy, SMA", beverages: "Coca-Cola, Nestle and chi limited", dairy: "WAMCO, ARLA and Nestle", frozenFoods: "", grainsStaples: "", emergingBrands: "Muamal table water" },
  { location: "Adamawa", categories: "Cereals Dairy", cereals: "Nasco and kellog", babyFoods: "", beverages: "", dairy: "WAMCO, kremela, kivo", frozenFoods: "", grainsStaples: "", emergingBrands: "Kremela" },
  { location: "Lagos", categories: "Dairy", cereals: "", babyFoods: "", beverages: "", dairy: "Peak milk, cowbell milk and holladia milk", frozenFoods: "", grainsStaples: "", emergingBrands: "Loyal milk, Good time, creamela, holladia milk, Dano milk" },
  { location: "Adamawa", categories: "Cereals Beverages Grains/Staples", cereals: "Nasco, kellogs", babyFoods: "", beverages: "Coca-Cola, Nestle, Chi limited", dairy: "", frozenFoods: "", grainsStaples: "Dangote, Olam, maize", emergingBrands: "Muamal table water" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages Frozen Foods", cereals: "Nasco, kellogs, fruit and fibre", babyFoods: "My boy, Nestle, SMA", beverages: "Nestle, Coca-Cola, Holladia", dairy: "", frozenFoods: "Chicken, turkey", grainsStaples: "", emergingBrands: "Kremela, good time" },
  { location: "Lagos", categories: "Cereals Baby Foods", cereals: "Kellogg Company, General Mills, Post Consumer Brands", babyFoods: "1. Nestlé S.A. 2. Danone S.A. 3. Abbott Laboratories", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Little Spoon, Serenity Kids, Once Upon a Farm, Cerebelly, Yumi" },
  { location: "Lagos", categories: "Cereals Beverages", cereals: "Cerelac, arilac and golden morn", babyFoods: "", beverages: "Bounvita, Milo and peak milk", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Kivo, nutrilac, nutribom" },
  { location: "Lagos", categories: "Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Dbull, honey well, BUA", emergingBrands: "Ayoola food, choice, Sunti Golden, wura food, FarmFix Grains" },
  { location: "Lagos", categories: "Cereals Baby Foods Beverages Dairy Frozen Foods", cereals: "1. Golden morn(Nestle Nigeria) 2. Kellogg's 3. Nasco", babyFoods: "1. Nestlé Nigeria (Cerelac, NAN, Lactogen) 2. SMA Nutrition 3. Aptamil (Danone)", beverages: "1. Nigerian Breweries Plc 2. Nigerian Bottling Company (NBC) 3. Seven-Up Bottling Company", dairy: "1. FrieslandCampina WAMCO Nigeria PLC 2. Promasidor Nigeria Limited 3. Chi Limited", frozenFoods: "1. DÉLIFROST Nigeria 2. Paramount Frozen Foods Ltd 3. UAC Foods Limited", grainsStaples: "", emergingBrands: "Imata Studios, Micohype Beauty Hair, Freak Vault Clothing" },
  { location: "Adamawa", categories: "Cereals Beverages Dairy Grains/Staples", cereals: "Kellogs, Nasco", babyFoods: "", beverages: "Coca-Cola, chi limited, chivita", dairy: "WAMCO, cowbell, ARLA", frozenFoods: "", grainsStaples: "Dangote, FMN, rice, maize", emergingBrands: "Kremela, Good time" },
  { location: "Benue", categories: "Baby Foods", cereals: "", babyFoods: "Golden mom, celiac and Cornflakes", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Nil" },
  { location: "Benue", categories: "Cereals Beverages", cereals: "Nutribom", babyFoods: "", beverages: "Coco cola, Malt, Milk", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Nutribom" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages Dairy Grains/Staples Others", cereals: "Nestle, golden morn, Quoker oat, nasco cornflakes", babyFoods: "Nestle NAN, Friesland Campina Wamco peak 123, SMA nutrition", beverages: "Coca-cola Nigeria, Pepsi of Seven up bottling company, cowbell", dairy: "Peak milk, Cowbell milk, Dano Milk", frozenFoods: "", grainsStaples: "Golden penny noodles, indomie noodles, Dangote noodles", emergingBrands: "Ruffles potato chips, plantain chips, Frandimore potato" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages Dairy Grains/Staples Others", cereals: "Nestle golden morn, Kellogg's corn flakes, Nestle Milo cereal", babyFoods: "Nestle Nigeria cerelac, Nestle Nigeria NAN, SMA nutrition", beverages: "Chi Limited Hollandia Yogurt, coca cola Nigeria coke, sevenup", dairy: "Friesland Campina Wamco, cowbell Nigeria, Fan milk plc", frozenFoods: "", grainsStaples: "Dangote pasta, Indomie noodles", emergingBrands: "So fresh, Agritech, crop2cash" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages Dairy Frozen Foods", cereals: "Golden Morn, Nasko Corn Flakes, Kellogs Cornflakes", babyFoods: "Nutribom, Nutrilac, My boy", beverages: "Milo, Bornvita, Ovaltine", dairy: "Peak Milk, Three Crowns, Dano", frozenFoods: "Not in stock", grainsStaples: "", emergingBrands: "I don't know" },
  { location: "Oyo", categories: "Cereals Beverages Dairy Grains/Staples", cereals: "Promasidor (Cowbell Cereals) Dangote Group Checkers Custard", babyFoods: "", beverages: "Coca cola, Bigi, Dangote Beverages", dairy: "Friesland Campina Wamco Nigeria, Chi Limited Nigeria, Fan milk", frozenFoods: "", grainsStaples: "Golden penny, Dangote Group, Royal stallion", emergingBrands: "Bigi, Dano Milk, Checkers Africa" },
  { location: "Oyo", categories: "Cereals", cereals: "Stallion rice, ofada boy, labana rice", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Agbofarms rice, Farmkonnect rice, Eagle foods rice" },
  { location: "Oyo", categories: "Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Bodija market, Moniya Market, Oje market", emergingBrands: "White beans, ofada rice, mokwa beans, millet, Sorghum" },
  { location: "Oyo", categories: "Dairy", cereals: "", babyFoods: "", beverages: "", dairy: "1. Fan Milk Plc, 2. FarmFresh Dairy Nigeria, 3. Oyo Dairy Farmers Cooperative", frozenFoods: "", grainsStaples: "", emergingBrands: "Ogunlana Dairy Farms, Ibadan Fresh Dairy, MilkyGold Nigeria" },
  { location: "Benue", categories: "Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Beans, Rice and Soybeans", emergingBrands: "Eggs" },
  { location: "Benue", categories: "Beverages", cereals: "", babyFoods: "", beverages: "Coca-Cola, PepsiCo, Nestlé", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Benfruit Plant, Benue Brewery Limited, Bogo Beverages Limited" },
  { location: "Benue", categories: "Cereals", cereals: "Golden Morn, Kellogg's Cornflakes, NASCO Cornflakes", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Sunvita Cereal, Nutraboom, Chow Foods Nigeria, Nutrend" },
  { location: "Benue", categories: "Cereals Beverages", cereals: "Golden Morn (Nestlé Nigeria), Kellogg's Cornflakes (Tolaram Group), NASCO Cornflakes", babyFoods: "", beverages: "The Coca-Cola Company, Benue Brewery Limited, Tito Yoghurt Company", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "More Lager Beer, Zeva Premium Lager Beer, Oyi Bitters" },
  { location: "Benue", categories: "Beverages", cereals: "", babyFoods: "", beverages: "Coca-Cola, Pepsi, Maltina", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Bigi Drinks, Fearless Energy Drink, Sosa Fruit Juice" },
  { location: "Lagos", categories: "Baby Foods", cereals: "", babyFoods: "Cerelac, my boy, NAN", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Nutrilac, nutribom" },
  { location: "Lagos", categories: "Frozen Foods", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "Turkey, chicken and titus", grainsStaples: "", emergingBrands: "Wings, lap, full chicken, shawa" },
  { location: "Lagos", categories: "Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Crown Flour Mills, BUA Foods plc, Flour Mills of Nigeria", emergingBrands: "A.R.N. Foods, Coscharis Rice, RiceAfrika" },
  { location: "Lagos", categories: "Beverages Others", cereals: "", babyFoods: "", beverages: "Coca-Cola, PepsiCo, Nestle", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Liquid Death, Olipop, Sunwink, Dash Water, C4 Energy" },
  { location: "Lagos", categories: "Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Olam Nigeria limited, Golden Penny Dangote flour", emergingBrands: "Vika foods, Tummy Tummy Grains, Crown premium, Releaf staples" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages Dairy Grains/Staples", cereals: "Nasco, kellogs, golden morn", babyFoods: "Nestle, peak 123, cerelac", beverages: "Coca-Cola, chivita, Amstel Malt", dairy: "Kerrygold, peak, cowbell", frozenFoods: "", grainsStaples: "Rice", emergingBrands: "" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages Dairy Grains/Staples", cereals: "Nasco, golden morn, kellogs", babyFoods: "Nestle, nutribom, cerelac", beverages: "Coca-Cola, chivita, Amstel malt", dairy: "Peak, cowbell, kerrygold", frozenFoods: "", grainsStaples: "Rice", emergingBrands: "Marvico foods" },
  { location: "Adamawa", categories: "Cereals Baby Foods Beverages Dairy Frozen Foods Grains/Staples", cereals: "Nestle, Nasco, quarker gold", babyFoods: "Nestle, myboy, sma gold", beverages: "Coca-Cola, Nigeria breweries, hollandia", dairy: "Peak, cowbell, kerry gold", frozenFoods: "Chicken", grainsStaples: "Rice", emergingBrands: "" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages", cereals: "Nestlé Nigeria (Golden morn) Kellogg's & Nasco conflakes Quaker oats", babyFoods: "Nestlé Nigeria Limited, Friesland Campina Wamco, Promasidor Nigeria", beverages: "Nigerian bottling company, Nigerian breweries plc, chi", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "New age beverages, pacesetters fruit processing, Orikis" },
  { location: "Oyo", categories: "Beverages", cereals: "", babyFoods: "", beverages: "Sevenup bottling company, Cocacola, Rite foods", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "The Exclusive Drinks, Urban Fruits, Optimum Drinks, YES Zobo Drink" },
  { location: "Benue", categories: "Cereals Beverages", cereals: "Kellogg's, Nestlé (Golden Morn), Nasco", babyFoods: "", beverages: "Coca‑Cola, Pepsi, and Fanta, 5 Alive, Nutrimilk, Chivita, Hollandia", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Bigi, Fearless Energy Drink, Monarch Beverages, Viju Industries" },
  { location: "Benue", categories: "Cereals Beverages", cereals: "Nestlé (Golden Morn, Cerelac), Sunvita (Promasidor), Dangote", babyFoods: "", beverages: "Coca‑Cola, Seven‑Up (PepsiCo), Nestlé (Milo, Nescafé)", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Zeva Beer, Bogo Beverages, Planet Drink, Farm Pride" },
  { location: "Benue", categories: "Cereals Baby Foods Beverages", cereals: "Golden Morn (Nestlé) Nasco Cornflakes Kellogg's", babyFoods: "Cerelac (Nestlé) Nutribom Friso Gold", beverages: "Milo Bournvita (Cadbury) Coca-Cola", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Checkers Custard, Fearless Energy Drink, Viju Milk" },
  { location: "Benue", categories: "Beverages", cereals: "", babyFoods: "", beverages: "Coca-Cola, Malt and Pop Cola", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Pop cola" },
  { location: "Benue", categories: "Grains/Staples", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Maize, Rice and Beans", emergingBrands: "Iron Pearl Millet, Soybeans, OFSP, VAC" },
  { location: "Benue", categories: "Beverages", cereals: "", babyFoods: "", beverages: "Coca‑Cola HBC, Seven‑Up Bottling Company, Nestlé", dairy: "", frozenFoods: "", grainsStaples: "", emergingBrands: "Zeva Beer, Bogo Beverages Limited, Planet Drink, Farm Pride" },
  { location: "Lagos", categories: "Cereals Grains/Staples", cereals: "Kellogg's, Nestlé Nigeria – Golden Morn, Nasco Group", babyFoods: "", beverages: "", dairy: "", frozenFoods: "", grainsStaples: "Flour Mills of Nigeria (FMN)", emergingBrands: "Ayoola Foods, Mafa Rice, Mama's Pride, Tana‑momo Foods" },
  { location: "Lagos", categories: "Frozen Foods", cereals: "", babyFoods: "", beverages: "", dairy: "", frozenFoods: "Zartech Limited", grainsStaples: "", emergingBrands: "Agricore Integrated Farms Ltd, Farmcrowdy Foods, Fenchurch Foods" },
  { location: "Oyo", categories: "Cereals Baby Foods Beverages Dairy", cereals: "Dangote group, Nestle Nigeria, Golden penny", babyFoods: "Frieslandcampina wamco, Danone Nutricia, SMA nutrition", beverages: "Nigerian breweries plc, Nigeria bottling company, Chi Limited", dairy: "Frieslandcampina wamco, Promasidor, Fan milk", frozenFoods: "", grainsStaples: "", emergingBrands: "Agrohive, Foodlocker, Heyfood, Obasanjo farm, Fanmilk" },
  { location: "Oyo", categories: "Cereals Dairy", cereals: "Kellogg's, Dangote group, Golden penny", babyFoods: "", beverages: "", dairy: "Friesland Campina Wamco Nigeria Plc, Fan milk plc, Promasidor (cowbell)", frozenFoods: "", grainsStaples: "", emergingBrands: "Nunu yogurt, Fanyogo yogurt, Obasanjo farm" },
];

export const tableHeaders = [
  "Location",
  "Which major food categories do you stock?",
  "Top 3 Market Leader for cereals",
  "Top 3 Market Leader for baby foods",
  "Top 3 Market Leader for beverages",
  "Top 3 Market Leader for dairy",
  "Top 3 Market Leader for frozen foods",
  "Top 3 Market Leader for grains/staples",
  "Emerging brands gaining visibility",
] as const;
